In [1]:
import pandas as pd

In [4]:
#1. import the provided dataset to dataframe (telecom_customer_churn.csv)
customer_df = pd.read_csv("3.6_Exercise_telecom_customer_churn.csv")
customer_df.head()

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [8]:
#2. change the settings to display all the columns
pd.set_option('display.max_columns', None)
#3. check the number of rows and columns
print(customer_df.shape)
#4. check the top 5 rows
customer_df.head()

(7043, 21)

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [9]:
#display all the column names
customer_df.columns

Index(['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents',
       'tenure', 'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'total_charges', 'churn'],
      dtype='str')

In [11]:
# Check if the dataset contains nulls
customer_df.isnull().sum()

customer_id          0
gender               0
senior_citizen       0
partner              0
dependents           0
tenure               0
phone_service        0
multiple_lines       0
internet_service     0
online_security      0
online_backup        0
device_protection    0
tech_support         0
streaming_tv         0
streaming_movies     0
contract             0
paperless_billing    0
payment_method       0
monthly_charges      0
total_charges        0
churn                0
dtype: int64

In [12]:
#check the datatype of all columns
customer_df.dtypes

customer_id              str
gender                   str
senior_citizen         int64
partner                  str
dependents               str
tenure                 int64
phone_service            str
multiple_lines           str
internet_service         str
online_security          str
online_backup            str
device_protection        str
tech_support             str
streaming_tv             str
streaming_movies         str
contract                 str
paperless_billing        str
payment_method           str
monthly_charges      float64
total_charges            str
churn                    str
dtype: object

In [13]:
# Fix the datatype
#convert the datatype of 'monthly_charges', 'total_charges', 'tenure' to numeric datatype (pd.to_numeric)
cols_to_num = ['monthly_charges', 'total_charges', 'tenure']
customer_df[cols_to_num] = customer_df[cols_to_num].apply(pd.to_numeric, errors='coerce')

In [16]:
#Q1 - Calculate the mean, median, and mode of the monthly_charges column
mean = customer_df["monthly_charges"].mean()
median = customer_df["monthly_charges"].median()
mode = customer_df["monthly_charges"].mode()

print(f"Mean: {mean:.2f}")
print(f"Median: {median:.2f}")
print(f"Mode: {mode[0]:.2f}")

Mean: 64.76
Median: 70.35
Mode: 20.05

In [17]:
# Q2 - Calculate the 25th, 50th, and 75th percentiles of the total_charges column ?

percentiles = customer_df['total_charges'].quantile([0.25, 0.5, 0.75])

print(f"25th Percentile: {percentiles[0.25]:.2f}")
print(f"50th Percentile: {percentiles[0.50]:.2f}")
print(f"75th Percentile: {percentiles[0.75]:.2f}")

25th Percentile: 401.45
50th Percentile: 1397.47
75th Percentile: 3794.74

In [19]:
# Q3 - Calculate the range of monthly_charges column?
# Hint - Range is the difference between max and min of monthly_charges.
range_monthly_charges = customer_df['monthly_charges'].max() - customer_df['monthly_charges'].min()
print('Range of monthly charges column:', range_monthly_charges)

Range of monthly charges column: 100.5

In [20]:
#Q4 - What is the first quartile of the monthly_charges column for customers who have not churned?
first_quartile_monthly_charges_not_churned = customer_df.loc[customer_df['churn'] == 'No', 'monthly_charges'].quantile(0.25)
print('First quartile of monthly charges column for customers who have not churned:', first_quartile_monthly_charges_not_churned)

First quartile of monthly charges column for customers who have not churned: 25.1

In [21]:
#Q5 - What is the third quartile of the total_charges column for customers who have churned?
third_quartile_total_charges_churned = customer_df.loc[customer_df['churn'] == 'Yes', 'total_charges'].quantile(0.75)
print('Third quartile of total charges column for customers who have churned:', third_quartile_total_charges_churned)

Third quartile of total charges column for customers who have churned: 2331.3

In [22]:
#Q6-  What is the mode of the payment method column for customers who have churned?
mode_payment_method_churned = customer_df.loc[customer_df['churn'] == 'Yes', 'payment_method'].mode()[0]
print('Mode of payment method column for customers who have churned:', mode_payment_method_churned)

Mode of payment method column for customers who have churned: Electronic check

In [23]:
#Q7 - What is the mean of the total charges column for customers who have churned and have a month-to-month contract?
# Filter the rows based on the churn status and contract type
filtered_df = customer_df.loc[(customer_df['churn'] == 'Yes') & (customer_df['contract'] == 'Month-to-month')]

# Calculate the mean of the total charges column
mean_total_charges = filtered_df['total_charges'].mean()

# Print the result
print('Mean of total charges column for customers who have churned and have a month-to-month contract:', mean_total_charges)

Mean of total charges column for customers who have churned and have a month-to-month contract: 1164.4605740181269

In [24]:
# Q8 - What is the median of the tenure column for customers who have not churned and have a two-year contract?
# Filter the rows based on the churn status and contract type
filtered_df = customer_df.loc[(customer_df['churn'] == 'No') & (customer_df['contract'] == 'Two year')]

# Calculate the median of the tenure column
median_tenure = filtered_df['tenure'].median()

# Print the result
print('Median of tenure column for customers who have not churned and have a two-year contract:', median_tenure)

Median of tenure column for customers who have not churned and have a two-year contract: 64.0