In [1]:
import pandas as pd

In [2]:
df_bookings = pd.read_csv("10.2_DataUnderstandingCSVFiles_fact_bookings.csv")
df_date = pd.read_csv('10.2_DataUnderstandingCSVFiles_dim_date.csv')
df_hotels = pd.read_csv('10.2_DataUnderstandingCSVFiles_dim_hotels.csv')
df_rooms = pd.read_csv('10.2_DataUnderstandingCSVFiles_dim_rooms.csv')
df_agg_bookings = pd.read_csv('10.2_DataUnderstandingCSVFiles_fact_aggregated_bookings.csv')

In [3]:
df_agg_bookings.head()

   property_id check_in_date room_category  successful_bookings  capacity
0        16559     01-May-22           RT1                   25      30.0
1        19562     01-May-22           RT1                   28      30.0
2        19563     01-May-22           RT1                   23      30.0
3        17558     01-May-22           RT1                   30      19.0
4        16558     01-May-22           RT1                   18      19.0

In [4]:
df_agg_bookings["occ_pct"] = df_agg_bookings["successful_bookings"]/df_agg_bookings["capacity"]

In [5]:
df_agg_bookings

,property_id,check_in_date,room_category,successful_bookings,capacity,occ_pct
0,16559,01-May-22,RT1,25,30.0,0.833333
1,19562,01-May-22,RT1,28,30.0,0.933333
2,19563,01-May-22,RT1,23,30.0,0.766667
3,17558,01-May-22,RT1,30,19.0,1.578947
4,16558,01-May-22,RT1,18,19.0,0.947368
...,...,...,...,...,...,...
9195,16563,31-Jul-22,RT4,13,18.0,0.722222
9196,16559,31-Jul-22,RT4,13,18.0,0.722222
9197,17558,31-Jul-22,RT4,3,6.0,0.500000
9198,19563,31-Jul-22,RT4,3,6.0,0.500000
9199,17561,31-Jul-22,RT4,3,4.0,0.750000

In [6]:
df_agg_bookings["occ_pct"] = df_agg_bookings["occ_pct"].apply(lambda x : round(x*100,2))
df_agg_bookings.head(5)

,property_id,check_in_date,room_category,successful_bookings,capacity,occ_pct
0,16559,01-May-22,RT1,25,30.0,83.33
1,19562,01-May-22,RT1,28,30.0,93.33
2,19563,01-May-22,RT1,23,30.0,76.67
3,17558,01-May-22,RT1,30,19.0,157.89
4,16558,01-May-22,RT1,18,19.0,94.74

In [7]:
# Some of Data Transformation Techniques

# Creating New Columns
# Normalization
# Merge
# Aggregation