In [1]:
import pandas as pd

In [2]:
df_bookings = pd.read_csv("10.2_DataUnderstandingCSVFiles_fact_bookings.csv")
df_date = pd.read_csv('10.2_DataUnderstandingCSVFiles_dim_date.csv')
df_hotels = pd.read_csv('10.2_DataUnderstandingCSVFiles_dim_hotels.csv')
df_rooms = pd.read_csv('10.2_DataUnderstandingCSVFiles_dim_rooms.csv')
df_agg_bookings = pd.read_csv('10.2_DataUnderstandingCSVFiles_fact_aggregated_bookings.csv')

In [3]:
df_agg_bookings["occ_pct"] = df_agg_bookings["successful_bookings"]/df_agg_bookings["capacity"]

In [4]:
df_agg_bookings["occ_pct"] = df_agg_bookings["occ_pct"].apply(lambda x : round(x*100,2))
df_agg_bookings.head(5)

,property_id,check_in_date,room_category,successful_bookings,capacity,occ_pct
0,16559,01-May-22,RT1,25,30.0,83.33
1,19562,01-May-22,RT1,28,30.0,93.33
2,19563,01-May-22,RT1,23,30.0,76.67
3,17558,01-May-22,RT1,30,19.0,157.89
4,16558,01-May-22,RT1,18,19.0,94.74

In [5]:
df_agg_bookings.groupby("room_category")["occ_pct"].mean()

room_category
RT1    58.224247
RT2    58.040278
RT3    58.028213
RT4    59.300461
Name: occ_pct, dtype: float64

In [6]:
df_agg_bookings.groupby("room_category")["occ_pct"].mean().round(2)

room_category
RT1    58.22
RT2    58.04
RT3    58.03
RT4    59.30
Name: occ_pct, dtype: float64

In [7]:
df_rooms

  room_id    room_class
0     RT1      Standard
1     RT2         Elite
2     RT3       Premium
3     RT4  Presidential

In [12]:
df = pd.merge(df_agg_bookings,df_rooms,left_on="room_category",right_on="room_id")
df.head(4)

,property_id,check_in_date,room_category,successful_bookings,capacity,occ_pct,room_id,room_class
0,16559,01-May-22,RT1,25,30.0,83.33,RT1,Standard
1,19562,01-May-22,RT1,28,30.0,93.33,RT1,Standard
2,19563,01-May-22,RT1,23,30.0,76.67,RT1,Standard
3,17558,01-May-22,RT1,30,19.0,157.89,RT1,Standard

In [13]:
df.groupby("room_class")["occ_pct"].mean().round(2)

room_class
Elite           58.04
Premium         58.03
Presidential    59.30
Standard        58.22
Name: occ_pct, dtype: float64

In [21]:
df.drop("room_id", axis=1, inplace=True, errors='ignore')
df.head(4)

,property_id,check_in_date,room_category,successful_bookings,capacity,occ_pct,room_class
0,16559,01-May-22,RT1,25,30.0,83.33,Standard
1,19562,01-May-22,RT1,28,30.0,93.33,Standard
2,19563,01-May-22,RT1,23,30.0,76.67,Standard
3,17558,01-May-22,RT1,30,19.0,157.89,Standard

**Print Average Occupany Rate Per City**

In [20]:
df_hotels.head()

   property_id  property_name  category    city
0        16558   Atliq Grands    Luxury   Delhi
1        16559  Atliq Exotica    Luxury  Mumbai
2        16560     Atliq City  Business   Delhi
3        16561      Atliq Blu    Luxury   Delhi
4        16562      Atliq Bay    Luxury   Delhi

In [22]:
df = pd.merge(df,df_hotels,on="property_id")
df.head(3)

,property_id,check_in_date,room_category,successful_bookings,capacity,occ_pct,room_class,property_name,category,city
0,16559,01-May-22,RT1,25,30.0,83.33,Standard,Atliq Exotica,Luxury,Mumbai
1,19562,01-May-22,RT1,28,30.0,93.33,Standard,Atliq Bay,Luxury,Bangalore
2,19563,01-May-22,RT1,23,30.0,76.67,Standard,Atliq Palace,Business,Bangalore

In [23]:
df.groupby("city")["occ_pct"].mean()

city
Bangalore    56.594207
Delhi        61.606467
Hyderabad    58.144651
Mumbai       57.936305
Name: occ_pct, dtype: float64

**When was occupancy better ? Weekday or weekend ?**

In [24]:
df_date

         date  mmm yy week no  day_type
0   01-May-22  May-22    W 19   weekend
1   02-May-22  May-22    W 19  weekeday
2   03-May-22  May-22    W 19  weekeday
3   04-May-22  May-22    W 19  weekeday
4   05-May-22  May-22    W 19  weekeday
..        ...     ...     ...       ...
87  27-Jul-22  Jul-22    W 31  weekeday
88  28-Jul-22  Jul-22    W 31  weekeday
89  29-Jul-22  Jul-22    W 31  weekeday
90  30-Jul-22  Jul-22    W 31   weekend
91  31-Jul-22  Jul-22    W 32   weekend

[92 rows x 4 columns]

In [30]:
df = pd.merge(df,df_date,left_on="check_in_date",right_on="date")
df.head(3)

,property_id,check_in_date,room_category,successful_bookings,capacity,occ_pct,room_class,property_name,category,city,date,mmm yy,week no,day_type
0,16559,01-May-22,RT1,25,30.0,83.33,Standard,Atliq Exotica,Luxury,Mumbai,01-May-22,May-22,W 19,weekend
1,19562,01-May-22,RT1,28,30.0,93.33,Standard,Atliq Bay,Luxury,Bangalore,01-May-22,May-22,W 19,weekend
2,19563,01-May-22,RT1,23,30.0,76.67,Standard,Atliq Palace,Business,Bangalore,01-May-22,May-22,W 19,weekend

In [32]:
df.groupby("day_type")["occ_pct"].mean().round(2)

day_type
weekeday    51.82
weekend     74.24
Name: occ_pct, dtype: float64

**In June What is occupancy for Different Cities**

In [33]:
df["mmm yy"].unique()

<StringArray>
['May-22', 'Jun-22', 'Jul-22']
Length: 3, dtype: str

In [35]:
df_june = df[df["mmm yy"]=="Jun-22"]
df_june

,property_id,check_in_date,room_category,successful_bookings,capacity,occ_pct,room_class,property_name,category,city,date,mmm yy,week no,day_type
3100,16559,01-Jun-22,RT1,14,30.0,46.67,Standard,Atliq Exotica,Luxury,Mumbai,01-Jun-22,Jun-22,W 23,weekeday
3101,18560,01-Jun-22,RT1,18,30.0,60.00,Standard,Atliq City,Business,Hyderabad,01-Jun-22,Jun-22,W 23,weekeday
3102,19562,01-Jun-22,RT1,18,30.0,60.00,Standard,Atliq Bay,Luxury,Bangalore,01-Jun-22,Jun-22,W 23,weekeday
3103,19563,01-Jun-22,RT1,14,30.0,46.67,Standard,Atliq Palace,Business,Bangalore,01-Jun-22,Jun-22,W 23,weekeday
3104,17558,01-Jun-22,RT1,8,19.0,42.11,Standard,Atliq Grands,Luxury,Mumbai,01-Jun-22,Jun-22,W 23,weekeday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6095,17562,30-Jun-22,RT4,3,6.0,50.00,Presidential,Atliq Bay,Luxury,Mumbai,30-Jun-22,Jun-22,W 27,weekeday
6096,19563,30-Jun-22,RT4,3,6.0,50.00,Presidential,Atliq Palace,Business,Bangalore,30-Jun-22,Jun-22,W 27,weekeday
6097,16560,30-Jun-22,RT4,3,7.0,42.86,Presidential,Atliq City,Business,Delhi,30-Jun-22,Jun-22,W 27,weekeday
6098,19558,30-Jun-22,RT4,3,7.0,42.86,Presidential,Atliq Grands,Luxury,Bangalore,30-Jun-22,Jun-22,W 27,weekeday
6099,17561,30-Jun-22,RT4,3,4.0,75.00,Presidential,Atliq Blu,Luxury,Mumbai,30-Jun-22,Jun-22,W 27,weekeday

In [38]:
df_june.groupby("city")["occ_pct"].mean().round(2).sort_values(ascending=False)

city
Delhi        61.46
Mumbai       57.79
Hyderabad    57.69
Bangalore    55.95
Name: occ_pct, dtype: float64

In [40]:
df_august =  pd.read_csv("10.7_InsightsGeneration.csv")
df_august

,property_id,property_name,category,city,room_category,room_class,check_in_date,mmm yy,week no,day_type,successful_bookings,capacity,occ%
0,16559,Atliq Exotica,Luxury,Mumbai,RT1,Standard,01-Aug-22,Aug-22,W 32,weekeday,30,30,100.00
1,19562,Atliq Bay,Luxury,Bangalore,RT1,Standard,01-Aug-22,Aug-22,W 32,weekeday,21,30,70.00
2,19563,Atliq Palace,Business,Bangalore,RT1,Standard,01-Aug-22,Aug-22,W 32,weekeday,23,30,76.67
3,19558,Atliq Grands,Luxury,Bangalore,RT1,Standard,01-Aug-22,Aug-22,W 32,weekeday,30,40,75.00
4,19560,Atliq City,Business,Bangalore,RT1,Standard,01-Aug-22,Aug-22,W 32,weekeday,20,26,76.92
5,17561,Atliq Blu,Luxury,Mumbai,RT1,Standard,01-Aug-22,Aug-22,W 32,weekeday,18,26,69.23
6,17564,Atliq Seasons,Business,Mumbai,RT1,Standard,01-Aug-22,Aug-22,W 32,weekeday,10,16,62.50

In [41]:
df_august.columns

Index(['property_id', 'property_name', 'category', 'city', 'room_category',
       'room_class', 'check_in_date', 'mmm yy', 'week no', 'day_type',
       'successful_bookings', 'capacity', 'occ%'],
      dtype='str')

In [42]:
df.columns

Index(['property_id', 'check_in_date', 'room_category', 'successful_bookings',
       'capacity', 'occ_pct', 'room_class', 'property_name', 'category',
       'city', 'date', 'mmm yy', 'week no', 'day_type'],
      dtype='str')

In [43]:
df_august.shape

(7, 13)

In [44]:
df.shape

(9200, 14)

In [45]:
latest_df = pd.concat([df,df_august],ignore_index=True,axis=0)
latest_df

,property_id,check_in_date,room_category,successful_bookings,capacity,occ_pct,room_class,property_name,category,city,date,mmm yy,week no,day_type,occ%
0,16559,01-May-22,RT1,25,30.0,83.33,Standard,Atliq Exotica,Luxury,Mumbai,01-May-22,May-22,W 19,weekend,NaN
1,19562,01-May-22,RT1,28,30.0,93.33,Standard,Atliq Bay,Luxury,Bangalore,01-May-22,May-22,W 19,weekend,NaN
2,19563,01-May-22,RT1,23,30.0,76.67,Standard,Atliq Palace,Business,Bangalore,01-May-22,May-22,W 19,weekend,NaN
3,17558,01-May-22,RT1,30,19.0,157.89,Standard,Atliq Grands,Luxury,Mumbai,01-May-22,May-22,W 19,weekend,NaN
4,16558,01-May-22,RT1,18,19.0,94.74,Standard,Atliq Grands,Luxury,Delhi,01-May-22,May-22,W 19,weekend,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9202,19563,01-Aug-22,RT1,23,30.0,NaN,Standard,Atliq Palace,Business,Bangalore,NaN,Aug-22,W 32,weekeday,76.67
9203,19558,01-Aug-22,RT1,30,40.0,NaN,Standard,Atliq Grands,Luxury,Bangalore,NaN,Aug-22,W 32,weekeday,75.00
9204,19560,01-Aug-22,RT1,20,26.0,NaN,Standard,Atliq City,Business,Bangalore,NaN,Aug-22,W 32,weekeday,76.92
9205,17561,01-Aug-22,RT1,18,26.0,NaN,Standard,Atliq Blu,Luxury,Mumbai,NaN,Aug-22,W 32,weekeday,69.23
9206,17564,01-Aug-22,RT1,10,16.0,NaN,Standard,Atliq Seasons,Business,Mumbai,NaN,Aug-22,W 32,weekeday,62.50

In [46]:
latest_df.shape

(9207, 15)

**Print Revenue Realized Per City**

In [47]:
df_hotels.head()

   property_id  property_name  category    city
0        16558   Atliq Grands    Luxury   Delhi
1        16559  Atliq Exotica    Luxury  Mumbai
2        16560     Atliq City  Business   Delhi
3        16561      Atliq Blu    Luxury   Delhi
4        16562      Atliq Bay    Luxury   Delhi

In [48]:
df_bookings.head()

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
0,May012216558RT11,16558,27-04-2022,01-05-2022,02-05-2022,-3.0,RT1,direct online,1.0,Checked Out,10010,10010
1,May012216558RT12,16558,30-04-2022,01-05-2022,02-05-2022,2.0,RT1,others,NaN,Cancelled,9100,3640
2,May012216558RT13,16558,28-04-2022,01-05-2022,04-05-2022,2.0,RT1,logtrip,5.0,Checked Out,9100000,9100
3,May012216558RT14,16558,28-04-2022,01-05-2022,02-05-2022,-2.0,RT1,others,NaN,Cancelled,9100,3640
4,May012216558RT15,16558,27-04-2022,01-05-2022,02-05-2022,4.0,RT1,direct online,5.0,Checked Out,10920,10920

In [50]:
df_bookings_all = pd.merge(df_bookings,df_hotels,on="property_id")
df_bookings_all

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized,property_name,category,city
0,May012216558RT11,16558,27-04-2022,01-05-2022,02-05-2022,-3.0,RT1,direct online,1.0,Checked Out,10010,10010,Atliq Grands,Luxury,Delhi
1,May012216558RT12,16558,30-04-2022,01-05-2022,02-05-2022,2.0,RT1,others,NaN,Cancelled,9100,3640,Atliq Grands,Luxury,Delhi
2,May012216558RT13,16558,28-04-2022,01-05-2022,04-05-2022,2.0,RT1,logtrip,5.0,Checked Out,9100000,9100,Atliq Grands,Luxury,Delhi
3,May012216558RT14,16558,28-04-2022,01-05-2022,02-05-2022,-2.0,RT1,others,NaN,Cancelled,9100,3640,Atliq Grands,Luxury,Delhi
4,May012216558RT15,16558,27-04-2022,01-05-2022,02-05-2022,4.0,RT1,direct online,5.0,Checked Out,10920,10920,Atliq Grands,Luxury,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134585,Jul312217564RT46,17564,29-07-2022,31-07-2022,03-08-2022,1.0,RT4,makeyourtrip,2.0,Checked Out,32300,32300,Atliq Seasons,Business,Mumbai
134586,Jul312217564RT47,17564,30-07-2022,31-07-2022,01-08-2022,-4.0,RT4,logtrip,2.0,Checked Out,38760,38760,Atliq Seasons,Business,Mumbai
134587,Jul312217564RT48,17564,30-07-2022,31-07-2022,02-08-2022,1.0,RT4,tripster,NaN,Cancelled,32300,12920,Atliq Seasons,Business,Mumbai
134588,Jul312217564RT49,17564,29-07-2022,31-07-2022,01-08-2022,2.0,RT4,logtrip,2.0,Checked Out,32300,32300,Atliq Seasons,Business,Mumbai
134589,Jul312217564RT410,17564,31-07-2022,31-07-2022,01-08-2022,2.0,RT4,makeyourtrip,NaN,Cancelled,32300,12920,Atliq Seasons,Business,Mumbai

In [52]:
df_bookings_all.groupby("city")["revenue_generated"].sum()

city
Bangalore    494828175
Delhi        378117540
Hyderabad    381400850
Mumbai       815385740
Name: revenue_generated, dtype: int64

**Print Month By Month Revenue**

In [54]:
df_bookings_all

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized,property_name,category,city
0,May012216558RT11,16558,27-04-2022,01-05-2022,02-05-2022,-3.0,RT1,direct online,1.0,Checked Out,10010,10010,Atliq Grands,Luxury,Delhi
1,May012216558RT12,16558,30-04-2022,01-05-2022,02-05-2022,2.0,RT1,others,NaN,Cancelled,9100,3640,Atliq Grands,Luxury,Delhi
2,May012216558RT13,16558,28-04-2022,01-05-2022,04-05-2022,2.0,RT1,logtrip,5.0,Checked Out,9100000,9100,Atliq Grands,Luxury,Delhi
3,May012216558RT14,16558,28-04-2022,01-05-2022,02-05-2022,-2.0,RT1,others,NaN,Cancelled,9100,3640,Atliq Grands,Luxury,Delhi
4,May012216558RT15,16558,27-04-2022,01-05-2022,02-05-2022,4.0,RT1,direct online,5.0,Checked Out,10920,10920,Atliq Grands,Luxury,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134585,Jul312217564RT46,17564,29-07-2022,31-07-2022,03-08-2022,1.0,RT4,makeyourtrip,2.0,Checked Out,32300,32300,Atliq Seasons,Business,Mumbai
134586,Jul312217564RT47,17564,30-07-2022,31-07-2022,01-08-2022,-4.0,RT4,logtrip,2.0,Checked Out,38760,38760,Atliq Seasons,Business,Mumbai
134587,Jul312217564RT48,17564,30-07-2022,31-07-2022,02-08-2022,1.0,RT4,tripster,NaN,Cancelled,32300,12920,Atliq Seasons,Business,Mumbai
134588,Jul312217564RT49,17564,29-07-2022,31-07-2022,01-08-2022,2.0,RT4,logtrip,2.0,Checked Out,32300,32300,Atliq Seasons,Business,Mumbai
134589,Jul312217564RT410,17564,31-07-2022,31-07-2022,01-08-2022,2.0,RT4,makeyourtrip,NaN,Cancelled,32300,12920,Atliq Seasons,Business,Mumbai

In [55]:
df_date["mmm yy"].unique()

<StringArray>
['May-22', 'Jun-22', 'Jul-22']
Length: 3, dtype: str

In [56]:
pd.merge(df_bookings_all,df_date,left_on="check_in_date",right_on="date")

Empty DataFrame
Columns: [booking_id, property_id, booking_date, check_in_date, checkout_date, no_guests, room_category, booking_platform, ratings_given, booking_status, revenue_generated, revenue_realized, property_name, category, city, date, mmm yy, week no, day_type]
Index: []

In [57]:
df_bookings_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 134590 entries, 0 to 134589
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   booking_id         134590 non-null  str
 1   property_id        134590 non-null  int64
 2   booking_date       134590 non-null  str
 3   check_in_date      134590 non-null  str
 4   checkout_date      134590 non-null  str
 5   no_guests          134587 non-null  float64
 6   room_category      134590 non-null  str
 7   booking_platform   134590 non-null  str
 8   ratings_given      56683 non-null   float64
 9   booking_status     134590 non-null  str
 10  revenue_generated  134590 non-null  int64
 11  revenue_realized   134590 non-null  int64
 12  property_name      134590 non-null  str
 13  category           134590 non-null  str
 14  city               134590 non-null  str
dtypes: float64(2), int64(3), str(10)
memory usage: 15.4 MB

In [58]:
df_date.info()

<class 'pandas.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      92 non-null     str
 1   mmm yy    92 non-null     str
 2   week no   92 non-null     str
 3   day_type  92 non-null     str
dtypes: str(4)
memory usage: 3.0 KB

In [61]:
df_date["date"] = pd.to_datetime(df_date["date"])
df_date

         date  mmm yy week no  day_type
0  2022-05-01  May-22    W 19   weekend
1  2022-05-02  May-22    W 19  weekeday
2  2022-05-03  May-22    W 19  weekeday
3  2022-05-04  May-22    W 19  weekeday
4  2022-05-05  May-22    W 19  weekeday
..        ...     ...     ...       ...
87 2022-07-27  Jul-22    W 31  weekeday
88 2022-07-28  Jul-22    W 31  weekeday
89 2022-07-29  Jul-22    W 31  weekeday
90 2022-07-30  Jul-22    W 31   weekend
91 2022-07-31  Jul-22    W 32   weekend

[92 rows x 4 columns]

In [63]:
# df_bookings_all["check_in_date"] = pd.to_datetime(df_bookings_all["check_in_date"])
df_bookings_all["check_in_date"] = pd.to_datetime(
    df_bookings_all["check_in_date"],
    format="%d-%m-%Y"
)
df_bookings_all

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized,property_name,category,city
0,May012216558RT11,16558,27-04-2022,2022-05-01,02-05-2022,-3.0,RT1,direct online,1.0,Checked Out,10010,10010,Atliq Grands,Luxury,Delhi
1,May012216558RT12,16558,30-04-2022,2022-05-01,02-05-2022,2.0,RT1,others,NaN,Cancelled,9100,3640,Atliq Grands,Luxury,Delhi
2,May012216558RT13,16558,28-04-2022,2022-05-01,04-05-2022,2.0,RT1,logtrip,5.0,Checked Out,9100000,9100,Atliq Grands,Luxury,Delhi
3,May012216558RT14,16558,28-04-2022,2022-05-01,02-05-2022,-2.0,RT1,others,NaN,Cancelled,9100,3640,Atliq Grands,Luxury,Delhi
4,May012216558RT15,16558,27-04-2022,2022-05-01,02-05-2022,4.0,RT1,direct online,5.0,Checked Out,10920,10920,Atliq Grands,Luxury,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134585,Jul312217564RT46,17564,29-07-2022,2022-07-31,03-08-2022,1.0,RT4,makeyourtrip,2.0,Checked Out,32300,32300,Atliq Seasons,Business,Mumbai
134586,Jul312217564RT47,17564,30-07-2022,2022-07-31,01-08-2022,-4.0,RT4,logtrip,2.0,Checked Out,38760,38760,Atliq Seasons,Business,Mumbai
134587,Jul312217564RT48,17564,30-07-2022,2022-07-31,02-08-2022,1.0,RT4,tripster,NaN,Cancelled,32300,12920,Atliq Seasons,Business,Mumbai
134588,Jul312217564RT49,17564,29-07-2022,2022-07-31,01-08-2022,2.0,RT4,logtrip,2.0,Checked Out,32300,32300,Atliq Seasons,Business,Mumbai
134589,Jul312217564RT410,17564,31-07-2022,2022-07-31,01-08-2022,2.0,RT4,makeyourtrip,NaN,Cancelled,32300,12920,Atliq Seasons,Business,Mumbai

In [66]:
df_bookings_all = pd.merge(df_bookings_all,df_date,left_on="check_in_date",right_on="date")
df_bookings_all

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized,property_name,category,city,date,mmm yy,week no,day_type
0,May012216558RT11,16558,27-04-2022,2022-05-01,02-05-2022,-3.0,RT1,direct online,1.0,Checked Out,10010,10010,Atliq Grands,Luxury,Delhi,2022-05-01,May-22,W 19,weekend
1,May012216558RT12,16558,30-04-2022,2022-05-01,02-05-2022,2.0,RT1,others,NaN,Cancelled,9100,3640,Atliq Grands,Luxury,Delhi,2022-05-01,May-22,W 19,weekend
2,May012216558RT13,16558,28-04-2022,2022-05-01,04-05-2022,2.0,RT1,logtrip,5.0,Checked Out,9100000,9100,Atliq Grands,Luxury,Delhi,2022-05-01,May-22,W 19,weekend
3,May012216558RT14,16558,28-04-2022,2022-05-01,02-05-2022,-2.0,RT1,others,NaN,Cancelled,9100,3640,Atliq Grands,Luxury,Delhi,2022-05-01,May-22,W 19,weekend
4,May012216558RT15,16558,27-04-2022,2022-05-01,02-05-2022,4.0,RT1,direct online,5.0,Checked Out,10920,10920,Atliq Grands,Luxury,Delhi,2022-05-01,May-22,W 19,weekend
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134585,Jul312217564RT46,17564,29-07-2022,2022-07-31,03-08-2022,1.0,RT4,makeyourtrip,2.0,Checked Out,32300,32300,Atliq Seasons,Business,Mumbai,2022-07-31,Jul-22,W 32,weekend
134586,Jul312217564RT47,17564,30-07-2022,2022-07-31,01-08-2022,-4.0,RT4,logtrip,2.0,Checked Out,38760,38760,Atliq Seasons,Business,Mumbai,2022-07-31,Jul-22,W 32,weekend
134587,Jul312217564RT48,17564,30-07-2022,2022-07-31,02-08-2022,1.0,RT4,tripster,NaN,Cancelled,32300,12920,Atliq Seasons,Business,Mumbai,2022-07-31,Jul-22,W 32,weekend
134588,Jul312217564RT49,17564,29-07-2022,2022-07-31,01-08-2022,2.0,RT4,logtrip,2.0,Checked Out,32300,32300,Atliq Seasons,Business,Mumbai,2022-07-31,Jul-22,W 32,weekend
134589,Jul312217564RT410,17564,31-07-2022,2022-07-31,01-08-2022,2.0,RT4,makeyourtrip,NaN,Cancelled,32300,12920,Atliq Seasons,Business,Mumbai,2022-07-31,Jul-22,W 32,weekend

In [67]:
df_bookings_all.groupby("mmm yy")["revenue_generated"].sum()

mmm yy
Jul-22    681711525
Jun-22    651939535
May-22    736081245
Name: revenue_generated, dtype: int64