In [22]:
import pandas as pd
df = pd.read_csv("9.4_HandleNAValues-Part1_weather_data.csv",parse_dates=["day"])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [5]:
type(df.day)

pandas.Series

In [6]:
type(df.day[0])

pandas.Timestamp

In [7]:
df.set_index('day',inplace=True)

In [19]:
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [20]:
# df.fillna(0,inplace=True)
df.fillna({
    'temperature': df.temperature.mean(),
    'windspeed':df.windspeed.mean(),
    'event': 'No Event'
}, inplace=True)
df

         day  temperature  windspeed     event
0 2017-01-01        32.00       6.00      Rain
1 2017-01-04        33.22       9.00     Sunny
2 2017-01-05        28.00       8.42      Snow
3 2017-01-06        33.22       7.00  No Event
4 2017-01-07        32.00       8.42      Rain
5 2017-01-08        33.22       8.42     Sunny
6 2017-01-09        33.22       8.42  No Event
7 2017-01-10        34.10       8.10    Cloudy
8 2017-01-11        40.00      12.00     Sunny

In [25]:
df.ffill()           #Fill Null value to its previous row value

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         32.0        9.0   Sunny
2 2017-01-05         28.0        9.0    Snow
3 2017-01-06         28.0        7.0    Snow
4 2017-01-07         32.0        7.0    Rain
5 2017-01-08         32.0        7.0   Sunny
6 2017-01-09         32.0        7.0   Sunny
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [27]:
df.bfill()           #Fill Null value to its next row value

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        9.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        8.1    Rain
5 2017-01-08         34.1        8.1   Sunny
6 2017-01-09         34.1        8.1  Cloudy
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [29]:
df.bfill(axis='columns')     #Fill Null value to its next column value

                   day temperature windspeed   event
0  2017-01-01 00:00:00        32.0       6.0    Rain
1  2017-01-04 00:00:00         9.0       9.0   Sunny
2  2017-01-05 00:00:00        28.0      Snow    Snow
3  2017-01-06 00:00:00         7.0       7.0     NaN
4  2017-01-07 00:00:00        32.0      Rain    Rain
5  2017-01-08 00:00:00       Sunny     Sunny   Sunny
6  2017-01-09 00:00:00         NaN       NaN     NaN
7  2017-01-10 00:00:00        34.1       8.1  Cloudy
8  2017-01-11 00:00:00        40.0      12.0   Sunny

In [31]:
df.bfill(limit=1)           #Fill Null value to its next row value for only next 1 Null Value

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        9.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09         34.1        8.1  Cloudy
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [32]:
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [41]:
df.select_dtypes(include='number').interpolate()    #Fill Null value to mid of next row value + previous row value

   temperature  windspeed
0         32.0      6.000
1         30.0      9.000
2         28.0      8.000
3         30.0      7.000
4         32.0      7.275
5         32.7      7.550
6         33.4      7.825
7         34.1      8.100
8         40.0     12.000

In [42]:
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [43]:
df.dropna(how="any")          #Drop row having atleast 1 NA Value

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [44]:
df.dropna(how="all")   #Drop row having All Value as NA

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [45]:
df.dropna(thresh=2)    #Drop row having atleast 2 NA Values

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny