In [2]:
import pandas as pd

In [2]:
df = pd.read_csv("9.5_HandleNAValues-Part2_weather_data.csv")
df

          day  temperature  windspeed     event
0  01-01-2017           32          6      Rain
1  01-02-2017       -99999          7     Sunny
2  01-03-2017           28     -99999      Snow
3  01-04-2017       -99999          7  no event
4  01-05-2017           32     -99999      Rain
5  01-06-2017           31          2     Sunny
6  01-06-2017           34     -88888  no event

In [3]:
df.replace(-99999,0)

          day  temperature  windspeed     event
0  01-01-2017           32          6      Rain
1  01-02-2017            0          7     Sunny
2  01-03-2017           28          0      Snow
3  01-04-2017            0          7  no event
4  01-05-2017           32          0      Rain
5  01-06-2017           31          2     Sunny
6  01-06-2017           34     -88888  no event

In [5]:
import numpy as np
df.replace(-99999,np.nan)

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [6]:
import numpy as np
df.replace([-99999,-88888],np.nan)

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  01-02-2017          NaN        7.0     Sunny
2  01-03-2017         28.0        NaN      Snow
3  01-04-2017          NaN        7.0  no event
4  01-05-2017         32.0        NaN      Rain
5  01-06-2017         31.0        2.0     Sunny
6  01-06-2017         34.0        NaN  no event

In [7]:
import numpy as np
df.replace(to_replace=[-99999,-88888],value=np.nan)

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  01-02-2017          NaN        7.0     Sunny
2  01-03-2017         28.0        NaN      Snow
3  01-04-2017          NaN        7.0  no event
4  01-05-2017         32.0        NaN      Rain
5  01-06-2017         31.0        2.0     Sunny
6  01-06-2017         34.0        NaN  no event

In [8]:
df

          day  temperature  windspeed     event
0  01-01-2017           32          6      Rain
1  01-02-2017       -99999          7     Sunny
2  01-03-2017           28     -99999      Snow
3  01-04-2017       -99999          7  no event
4  01-05-2017           32     -99999      Rain
5  01-06-2017           31          2     Sunny
6  01-06-2017           34     -88888  no event

In [9]:
df.replace({
    "temperature":-99999,
    "windspeed":[-99999,-88888],
    "event":"no event"
},np.nan)

          day  temperature  windspeed  event
0  01-01-2017         32.0        6.0   Rain
1  01-02-2017          NaN        7.0  Sunny
2  01-03-2017         28.0        NaN   Snow
3  01-04-2017          NaN        7.0    NaN
4  01-05-2017         32.0        NaN   Rain
5  01-06-2017         31.0        2.0  Sunny
6  01-06-2017         34.0        NaN    NaN

In [10]:
df.replace({
    -99999:np.nan,
    -88888:np.nan,
    "event":'sunny'
})

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  01-02-2017          NaN        7.0     Sunny
2  01-03-2017         28.0        NaN      Snow
3  01-04-2017          NaN        7.0  no event
4  01-05-2017         32.0        NaN      Rain
5  01-06-2017         31.0        2.0     Sunny
6  01-06-2017         34.0        NaN  no event

In [4]:
df = pd.DataFrame({
    'score':['exceptional','average','good','poor','average','exceptional'],
    'student':['rob','maya','parthiv','tom','julian','erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [6]:
df.replace(['poor','average','good','exceptional'],[1,2,3,4])

  score  student
0     4      rob
1     2     maya
2     3  parthiv
3     1      tom
4     2   julian
5     4    erica