In [1]:
import pandas as pd

In [8]:
india_weather =pd.DataFrame({
    "city":["Mumbai","Delhi","Banglore"],
    "temperature":[32,45,30],
    "humidity":[80,60,78]
})
india_weather

       city  temperature  humidity
0    Mumbai           32        80
1     Delhi           45        60
2  Banglore           30        78

In [9]:
us_weather =pd.DataFrame({
    "city":["New York","Chicago","Orlando"],
    "temperature":[21,14,35],
    "humidity":[68,65,75]
})
us_weather

       city  temperature  humidity
0  New York           21        68
1   Chicago           14        65
2   Orlando           35        75

In [12]:
pd.concat([india_weather,us_weather])

       city  temperature  humidity
0    Mumbai           32        80
1     Delhi           45        60
2  Banglore           30        78
0  New York           21        68
1   Chicago           14        65
2   Orlando           35        75

In [13]:
pd.concat([india_weather,us_weather],ignore_index=True)

       city  temperature  humidity
0    Mumbai           32        80
1     Delhi           45        60
2  Banglore           30        78
3  New York           21        68
4   Chicago           14        65
5   Orlando           35        75

In [18]:
df=pd.concat([india_weather,us_weather],keys=["India","US"])
df

             city  temperature  humidity
India 0    Mumbai           32        80
      1     Delhi           45        60
      2  Banglore           30        78
US    0  New York           21        68
      1   Chicago           14        65
      2   Orlando           35        75

In [19]:
df.loc["India"]

       city  temperature  humidity
0    Mumbai           32        80
1     Delhi           45        60
2  Banglore           30        78

In [20]:
df.loc["US"]

       city  temperature  humidity
0  New York           21        68
1   Chicago           14        65
2   Orlando           35        75

In [24]:
temerature_df =pd.DataFrame({
    "city":["Mumbai","Delhi","Banglore"],
    "temperature":[32,45,30],
},index=[0,1,2])
temerature_df

       city  temperature
0    Mumbai           32
1     Delhi           45
2  Banglore           30

In [23]:
windspeed_df =pd.DataFrame({
    "city":["Delhi","Mumbai"],
    "windspeed":[7,12],
},index=[1,0])
windspeed_df

     city  windspeed
1   Delhi          7
0  Mumbai         12

In [26]:
pd.concat([temerature_df,windspeed_df],axis=1)

       city  temperature    city  windspeed
0    Mumbai           32  Mumbai       12.0
1     Delhi           45   Delhi        7.0
2  Banglore           30     NaN        NaN

In [31]:
df1 =pd.DataFrame({
    "city":["New York","Chicago","Orlando"],
    "temperature":[21,14,35],
})
df1

       city  temperature
0  New York           21
1   Chicago           14
2   Orlando           35

In [32]:
df2 =pd.DataFrame({
    "city":["Chicago","New York","Orlando"],
    "humdity":[65,68,75],
})
df2

       city  humdity
0   Chicago       65
1  New York       68
2   Orlando       75

In [33]:
pd.merge(df1,df2)

       city  temperature  humdity
0  New York           21       68
1   Chicago           14       65
2   Orlando           35       75

In [35]:
df3=pd.merge(df1,df2,on="city")
df3

       city  temperature  humdity
0  New York           21       68
1   Chicago           14       65
2   Orlando           35       75

In [36]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35, 38],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [37]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "humidity": [65,68,71],
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [40]:
df3=pd.merge(df1,df2,on="city") # bydefault inner join
df3

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

In [41]:
df3=pd.merge(df1,df2,on="city",how="inner")
df3

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

In [42]:
df3=pd.merge(df1,df2,on="city",how="left")
df3

        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35       NaN
3  baltimore           38       NaN

In [43]:
df3=pd.merge(df1,df2,on="city",how="right")
df3

        city  temperature  humidity
0    chicago         14.0        65
1   new york         21.0        68
2  san diego          NaN        71

In [45]:
df3=pd.merge(df1,df2,on="city",how="outer") # Full Outer Join
df3

        city  temperature  humidity
0  baltimore         38.0       NaN
1    chicago         14.0      65.0
2   new york         21.0      68.0
3    orlando         35.0       NaN
4  san diego          NaN      71.0